name = "garisale-domain-router"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
  routes = [
    { pattern = "*.garisale.com/*", zone_name = "garisale.com" }
  ]

  kv_namespaces = [
    { binding = "DOMAIN_CACHE", id = "5d6680577b8749e3856671f96866e19e" }
  ]

  [env.production.vars]
    VERCEL_APP_URL = "https://dealer.garisale.com"

[env.staging]
  routes = [
    { pattern = "*.staging.garisale.com/*", zone_name = "garisale.com" }
  ]

  kv_namespaces = [
    { binding = "DOMAIN_CACHE", id = "8eb2bc47b6de4e07b5f062862483ec05" }
  ]

  [env.staging.vars]
    VERCEL_APP_URL = "https://dealer.staging.garisale.com"
